### ISSUE TITLE
CLA doesn't appear to apply to discussion in a CG, or any CG document that isn't a Specification

### ISSUE THREAD

**Issue by hober** [w3c/cg-council#1]
The [CBGP](https://www.w3.org/community/about/agreements/) says:

> Community Group deliverables may be anything, including documents, test suites, tutorials, demos, code, discussion, etc[…]
> 
> The label “Community Group Report” refers to any document produced by a Group. Some Community Group Reports are Specifications. The following rules apply to Specifications:
> 
>   * drafts are governed by Community Contributor License Agreement (CLA). W3C will provide a template for including copyright information.

and the CLA uses the term Specification throughout.

I think this means that non-Specification documents, test suites, tutorials, code, and discussion within a CG are not covered by the CLA. Is this intentional?

See https://github.com/privacycg/privacycg.github.io/pull/14#discussion_r401258357 for a case of this concern coming up in the context of a CG.

**Comment by dbaron** [comment]
Another important case of a possibly-Specification document that's not totally clear is explainers.

**Comment by ianbjacobs** [comment]
Hi @hober, 

It was intentional in the design of Community Groups that the CLA be limited to Specifications. 

This is analogous to the Working Group patent policy, which applies to the text of Recommendations (and not test suites, discussion, code, etc.)

Not all Community Group Reports (e.g., explainers) are specifications. The goal was for the CLA to (only) cover those CG Reports that are specifications, that is: things that get implemented in code.

Ian

**Comment by hober** [comment]
Okay, thanks for the clarification.
